
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s25/team02-s25-01
owner: ucsb-cs156-s25
repo_name: team02-s25-01
pull_requests: [{"author":{"id":"U_kgDOBYMMkw","is_bot":false,"login":"EyobTe","name":""},"headRefName":"eyobte-copy-backend-MenuItem","number":62,"title":"eyobte - copy backend CRUD operations from team01","url":"https://github.com/ucsb-cs156-s25/team02-s25-01/pull/62"},{"author":{"id":"U_kgDOCML-SQ","is_bot":false,"login":"alecsekimoto1","name":""},"headRefName":"as-RecommendationRequest-backend","number":61,"title":"as - copy backend CRUD operations from team01 for RecommendationReque…","url":"https://github.com/ucsb-cs156-s25/team02-s25-01/pull/61"}]
