
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s25/team02-s25-01
owner: ucsb-cs156-s25
repo_name: team02-s25-01
pull_requests: [{"author":{"id":"U_kgDOCML-SQ","is_bot":false,"login":"alecsekimoto1","name":""},"headRefName":"as-RecommendationRequest-integration-tests","number":127,"title":"as - add integration tests for RecommendationRequest Controller endpoints","url":"https://github.com/ucsb-cs156-s25/team02-s25-01/pull/127"},{"author":{"id":"U_kgDOCeRySA","is_bot":false,"login":"llexuan","name":""},"headRefName":"lexuan-ucsborganization-e2e-tests","number":125,"title":"Added end to end test","url":"https://github.com/ucsb-cs156-s25/team02-s25-01/pull/125"},{"author":{"id":"U_kgDOBtQNyQ","is_bot":false,"login":"rankesterc","name":"Ran Chen"},"headRefName":"rankesterc-articles-02-6","number":117,"title":"Added index page for placeholder article file","url":"https://github.com/ucsb-cs156-s25/team02-s25-01/pull/117"},{"author":{"id":"U_kgDOB3Dlbw","is_bot":false,"login":"hjin133","name":""},"headRefName":"hj-helprequest-e2e-tests","number":109,"title":"Hj helprequest e2e tests","url":"https://github.com/ucsb-cs156-s25/team02-s25-01/pull/109"},{"author":{"id":"U_kgDOBtQNyQ","is_bot":false,"login":"rankesterc","name":"Ran Chen"},"headRefName":"rankesterc-articles-02-5","number":95,"title":"Added article tables","url":"https://github.com/ucsb-cs156-s25/team02-s25-01/pull/95"},{"author":{"id":"U_kgDOBtQNyQ","is_bot":false,"login":"rankesterc","name":"Ran Chen"},"headRefName":"rankesterc-articles-02-4","number":91,"title":"Article Form and tests ","url":"https://github.com/ucsb-cs156-s25/team02-s25-01/pull/91"}]
