
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s25/team02-s25-01
owner: ucsb-cs156-s25
repo_name: team02-s25-01
pull_requests: [{"author":{"id":"U_kgDOBYMMkw","is_bot":false,"login":"EyobTe","name":""},"headRefName":"eyobte-menuItem-e2e","number":123,"title":"eyobte - made new e2e branch and created a e2e integration test for U…","url":"https://github.com/ucsb-cs156-s25/team02-s25-01/pull/123"},{"author":{"id":"U_kgDOCeRySA","is_bot":false,"login":"llexuan","name":""},"headRefName":"lexuan-ucsborganization-integration-tests","number":119,"title":"Lexuan ucsborganization integration tests","url":"https://github.com/ucsb-cs156-s25/team02-s25-01/pull/119"},{"author":{"id":"U_kgDOBtQNyQ","is_bot":false,"login":"rankesterc","name":"Ran Chen"},"headRefName":"rankesterc-articles-02-6","number":117,"title":"Added index page for placeholder article file","url":"https://github.com/ucsb-cs156-s25/team02-s25-01/pull/117"},{"author":{"id":"U_kgDOBYMMkw","is_bot":false,"login":"EyobTe","name":""},"headRefName":"eyobte-menuItems-e2e-tests","number":113,"title":"Eyobte menu items e2e tests","url":"https://github.com/ucsb-cs156-s25/team02-s25-01/pull/113"},{"author":{"id":"U_kgDOB3Dlbw","is_bot":false,"login":"hjin133","name":""},"headRefName":"hj-helprequest-e2e-tests","number":109,"title":"Hj helprequest e2e tests","url":"https://github.com/ucsb-cs156-s25/team02-s25-01/pull/109"},{"author":{"id":"U_kgDOB3Dlbw","is_bot":false,"login":"hjin133","name":""},"headRefName":"hj-helprequest-integration-tests","number":107,"title":"Hj helprequest integration tests","url":"https://github.com/ucsb-cs156-s25/team02-s25-01/pull/107"},{"author":{"id":"U_kgDOBYMMkw","is_bot":false,"login":"EyobTe","name":""},"headRefName":"eyobte-integrationTest-team03","number":96,"title":"Eyobte integration test team03","url":"https://github.com/ucsb-cs156-s25/team02-s25-01/pull/96"},{"author":{"id":"U_kgDOBtQNyQ","is_bot":false,"login":"rankesterc","name":"Ran Chen"},"headRefName":"rankesterc-articles-02-5","number":95,"title":"Added article tables","url":"https://github.com/ucsb-cs156-s25/team02-s25-01/pull/95"},{"author":{"id":"U_kgDOBtQNyQ","is_bot":false,"login":"rankesterc","name":"Ran Chen"},"headRefName":"rankesterc-articles-02-4","number":91,"title":"Article Form and tests ","url":"https://github.com/ucsb-cs156-s25/team02-s25-01/pull/91"},{"author":{"id":"U_kgDOBtQNyQ","is_bot":false,"login":"rankesterc","name":"Ran Chen"},"headRefName":"rankesterc-articles-02-2","number":71,"title":"Create articleFixtures.js and added four article examples","url":"https://github.com/ucsb-cs156-s25/team02-s25-01/pull/71"}]
