
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s25/team02-s25-01
owner: ucsb-cs156-s25
repo_name: team02-s25-01
pull_requests: [{"author":{"id":"U_kgDOBYMMkw","is_bot":false,"login":"EyobTe","name":""},"headRefName":"eyobte-menuItem-form","number":66,"title":"Eyobte menu item form","url":"https://github.com/ucsb-cs156-s25/team02-s25-01/pull/66"},{"author":{"id":"MDQ6VXNlcjkxNDk3ODM2","is_bot":false,"login":"oscar-luna","name":"Oscar Luna"},"headRefName":"oscar-MenuItemReview-backend","number":65,"title":" copy backend crud op from team01 for MenuItemReview","url":"https://github.com/ucsb-cs156-s25/team02-s25-01/pull/65"},{"author":{"id":"U_kgDOB3Dlbw","is_bot":false,"login":"hjin133","name":""},"headRefName":"hj-copy-backend-for-helprequest","number":64,"title":"hj - copy backend CRUD operations for helprequest table","url":"https://github.com/ucsb-cs156-s25/team02-s25-01/pull/64"},{"author":{"id":"U_kgDOBYMMkw","is_bot":false,"login":"EyobTe","name":""},"headRefName":"eyobte-MenuItem-fixtures","number":63,"title":"Eyobte - adding javascript for menu item fixtures","url":"https://github.com/ucsb-cs156-s25/team02-s25-01/pull/63"},{"author":{"id":"U_kgDOBYMMkw","is_bot":false,"login":"EyobTe","name":""},"headRefName":"eyobte-copy-backend-MenuItem","number":62,"title":"eyobte - copy backend CRUD operations from team01","url":"https://github.com/ucsb-cs156-s25/team02-s25-01/pull/62"}]
